language: python

python:
  - "3.5"

env:
  - PYTHON_TEST_VERSION=2.7
  - PYTHON_TEST_VERSION=3.5
  - PYTHON_TEST_VERSION=3.6

install:
  # The following control which earthio is part of build /test
  - export EARTHIO_VERSION=master # branch or tag of earthio
  # The following controls whether earthio is
  # * installed from setup.py - use "git"
  # * installed from conda build - use "conda"
  - export EARTHIO_INSTALL_METHOD="git" # or "conda"
  # Name of test env
  - export EARTHIO_TEST_ENV=earth-test-env
  # Where is the test data stored - don't put it in elm or earthio folders
  - export ELM_EXAMPLE_DATA_PATH=/tmp/elm-data
  - if [ "$IGNORE_ELM_DATA_DOWNLOAD" = "" ]; then mkdir -p $ELM_EXAMPLE_DATA_PATH; rm -rf $ELM_EXAMPLE_DATA_PATH/*;fi
  - MAKE_MINICONDA=1 . build_elm_env.sh

script:
  - cd $ELM_BUILD_DIR
  - echo ELM_EXAMPLE_DATA_PATH is $ELM_EXAMPLE_DATA_PATH
  - py.test -m 'not slow' -v
  - if [ "$IGNORE_ELM_DATA_DOWNLOAD" = "" ]; then rm -rf $ELM_EXAMPLE_DATA_PATH/*;fi
