language: python
python:
  - "3.5"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes true
  - conda install conda conda-build
  - conda env update || conda env create
  - source activate elm
  - conda build conda.recipe
  - mkdir LADSWEB
  - python setup.py develop

script:
  - LADSWEB_LOCAL_CACHE=LADSWEB DASK_SCHEDULER=SERIAL py.test -m 'not slow'


