dist: trusty
matrix:
  include:
  - os: osx
    env: PYTHON=3.6 NUMPY=1.12
  - env: PYTHON=3.6 NUMPY=1.12
  - env: PYTHON=3.5 NUMPY=1.11
  - env: PYTHON=3.4 NUMPY=1.10
  - env: PYTHON=2.7 NUMPY=1.9
branches:
  only:
  - master
before_install:
- export EARTHIO_VERSION=master
- export EARTHIO_INSTALL_METHOD="conda"
- export EARTHIO_TEST_ENV=earth-test-env
- export ELM_EXAMPLE_DATA_PATH=/tmp/elm-data
- export EARTHIO_CHANNEL_STR=" -c ioam -c conda-forge -c scitools/label/dev "
- mkdir -p $ELM_EXAMPLE_DATA_PATH; rm -rf $ELM_EXAMPLE_DATA_PATH/*
install:
- MAKE_MINICONDA=1 . build_elm_env.sh
script:
- cd $ELM_BUILD_DIR
- echo ELM_EXAMPLE_DATA_PATH is $ELM_EXAMPLE_DATA_PATH
- py.test -m 'not slow' -v
- rm -rf $ELM_EXAMPLE_DATA_PATH/*
notifications:
  email: false
  on_success: change
  on_failure: always
  flowdock:
    secure: "ZWA9YrhDi9SQKSbjgEyl6cx1XgDDGASJz3PDOV+94kMjQpZvpTus+Z913wrpWw1FoerzieX5bDOM0gryszW6qHDrIg3eopFKGI+r9Hpm8pNxAN3PFwZMswpjE54yfVOLLVjW0/e9JbYtTUcn3mIwVIEHmzdiwI8CjPhrXs9B2r9c1YWWFi6iJIscrNvAirmiuTuPqzqxyF/MQK6VLwTJGRy3qmO1v/UfW3ohn4PDL1hUSZQTXcfsJQTmOlc2sJFO8VnzwN/phwck/XbNf8wFVROQm2J//PW9te8siwq/ttNk2ip7RYstvab16z1fQaeenZWiEz6GKEk2G3ZcItyA5SRdALHgObPWvbDAF+TUI42KG+WgiaC3qgxLw0hQNah+sFLUQIbI1salypE3u1lNIMgxj3PMLs0+WU1lQA49JvyOObL2oo62wPZB5p3vmhUBdIWpVjailH2fgpIYe/eZ7WQRPh0oUe8+xek1AER/mV1NyshOWz6MRvUUBT12gLgNM2n2Ogz2ixjP8VXoRECewXYjkLIOKahqxObQYwBGjFZKbNhBm4Adwc3KXXf6paYGpRDcbSyNNxZ7Tv/FyVgxnN2+O+FKKXfFgax9568Pzj1z4oqDLwXLpv2ecUYTVNPOlzjOGFc+IrGDbzr9PKn4SXsrLErc5xZKEXE6hNFywO8="
