language: python

python:
  - "3.5"

env:
  - PYTHON_TEST_VERSION=2.7
  - PYTHON_TEST_VERSION=3.5
  - PYTHON_TEST_VERSION=3.6

install:
  # The following control which earthio is part of build /test
  - export EARTHIO_VERSION=fix-travis-data-download # branch or tag
  - export EARTHIO_INSTALL_METHOD="conda" # or "git"
  - MAKE_MINICONDA=1 . build_elm_env.sh

script:
  - cd $ELM_BUILD_DIR
  - echo ELM_EXAMPLE_DATA_PATH is $ELM_EXAMPLE_DATA_PATH
  - echo And ls of that dir is $(ls -lrth ELM_EXAMPLE_DATA_PATH)
  - py.test -m 'not slow' -v
