language: python

python:
  - "3.5"

env:
  - EARTH_VERS=2.7
  - EARTH_VERS=3.5
  - EARTH_VERS=3.6

install:
  - export ELM_BUILD_DIR=`pwd -P`
  - git clone http://github.com/ContinuumIO/earthio && cd earthio
  - MAKE_MINICONDA=1 . build_earthio_env.sh
  - python setup.py develop

script:
  - cd $ELM_BUILD_DIR
  - echo ELM_EXAMPLE_DATA_PATH is $ELM_EXAMPLE_DATA_PATH
  - echo And ls of that dir is $(ls -lrth ELM_EXAMPLE_DATA_PATH)
  - py.test -m 'not slow' -v
