name: elm
dependencies:
 - python=3.5
 - bokeh
 - dask
 - distributed
 - gdal
 - h5py
 - jupyter
 - matplotlib
 - netcdf4
 - networkx
 - numba
 - numpy
 - pandas
 - pytest
 - rasterio
 - requests
 - scikit-image
 - scikit-learn
 - scipy
 - tblib
 - xarray
 - yaml
 - pip:
   - deap
   - graphviz
   - pysptools