name: elm-env-27
channels:
 - conda-forge # essential for rasterio on osx
dependencies:
 - python=2.7
 - attrs
 - bokeh
 - dask
 - datashader
 - dill
 - distributed
 - jupyter
 - krb5
 - matplotlib
 - networkx
 - numba
 - numpy
 - pandas
 - pyproj
 - pytest
 - rasterio
 - requests
 - scikit-image
 - scikit-learn
 - scipy
 - shapely
 - statsmodels
 - tblib
 - xarray
 - yaml
 - six
 - pip:
   - deap==1.0.1
   - graphviz
   - pysptools
   - pypandoc
   - geopy
   - descartes
   - zict
   - pytest-rerunfailures
