name: elm-env
channels:
 - conda-forge # essential for rasterio on osx
dependencies:
 - attrs
 - bokeh
 - dask
 - datashader
 - dill
 - distributed
 - jupyter
 - krb5
 - matplotlib
 - networkx
 - numba
 - numpy
 - pandas
 - pyproj
 - pytest
 - python
 - rasterio
 - requests
 - scikit-image
 - scikit-learn
 - scipy
 - shapely
 - statsmodels
 - tblib
 - yaml
 - six
 - bioconda::deap
 - sphinx # for docs
 - sphinx_rtd_theme # for docs
 - numpydoc # for docs
 - pip:
   - graphviz
   - pysptools
   - pypandoc
   - geopy
   - descartes
   - zict
   - pytest-rerunfailures
   - dask-glm
   - dask-searchcv
   - recommonmark # for docs
   - sphinx-view # for docs
   - git+https://github.com/pydata/xarray.git
   - git+https://github.com/ContinuumIO/earthio.git # for docs
   - git+https://github.com/ContinuumIO/xarray_filters.git # for docs
