data_sources:
  NPP_DSRF1KD_L2GD:
    band_specs:
    - {name: band_1, search_key: long_name, search_value: 'Band 1 '}
    - {name: band_2, search_key: long_name, search_value: 'Band 2 '}
    - {name: band_3, search_key: long_name, search_value: 'Band 3 '}
    - {name: band_4, search_key: long_name, search_value: 'Band 4 '}
    - {name: band_5, search_key: long_name, search_value: 'Band 5 '}
    - {name: band_6, search_key: long_name, search_value: 'Band 6 '}
    - {name: band_7, search_key: long_name, search_value: 'Band 7 '}
    - {name: band_9, search_key: long_name, search_value: 'Band 9 '}
    - {name: band_10, search_key: long_name, search_value: 'Band 10 '}
    - {name: band_11, search_key: long_name, search_value: 'Band 11 '}
    batch_size: 1440000
    file_pattern: .*\.hdf
    reader: hdf4_example
    sample_args_generator: iter_files_recursively
    sample_from_args_func: elm.sample_util.samplers:image_selection
    selection_kwargs: {metadata_filter: 'elm.sample_util.metadata_selection:example_meta_is_day',
      top_dir: 'env:ELM_EXAMPLE_DATA_PATH'}
ensembles:
  no_ensemble: {init_ensemble_size: 1, ngen: 1, partial_fit_batches: 1, saved_ensemble_size: 1}
model_scoring:
  kmeans_aic:
    score_weights: [-1]
    scoring: elm.model_selection.kmeans:kmeans_aic
model_selection:
  kmeans_model_averaging:
    func: elm.model_selection.kmeans:kmeans_model_averaging
    kwargs: {drop_n: 0, evolve_n: 1, init_n: 0}
pipeline:
- data_source: NPP_DSRF1KD_L2GD
  sample_pipeline:
  - {flatten: C}
  - {random_sample: 1000}
  steps:
  - {method: fit, transform: pca}
predict:
  kmeans: {}
readers:
  hdf4_example: {load_array: 'elm.readers.hdf4:load_hdf4_array', load_meta: 'elm.readers.hdf4:load_hdf4_meta'}
sample_args_generators: {iter_files_recursively: 'elm.readers.local_file_iterators:iter_files_recursively',
  tif_file_gen: 'elm.readers.local_file_iterators:iter_dirs_of_dirs'}
train:
  kmeans:
    ensemble: no_ensemble
    model_init_class: sklearn.cluster:MiniBatchKMeans
    model_init_kwargs: {compute_labels: true}
    model_scoring: kmeans_aic
    model_selection: kmeans_model_averaging
    output_tag: kmeans
transform:
  pca:
    data_source: NPP_DSRF1KD_L2GD
    ensemble: no_ensemble
    model_init_class: sklearn.decomposition:MiniBatchSparsePCA
    model_init_kwargs: {alpha: 1, batch_size: 1000, callback: null, method: lars,
      n_components: 1, n_iter: 100, n_jobs: 4, random_state: null, ridge_alpha: 0.01,
      shuffle: true, verbose: false}
