data_sources:
  NPP_DSRF1KD_L2GD:
    band_specs:
    - {name: band_1, search_key: long_name, search_value: 'Band 1 '}
    - {name: band_2, search_key: long_name, search_value: 'Band 2 '}
    - {name: band_3, search_key: long_name, search_value: 'Band 3 '}
    - {name: band_4, search_key: long_name, search_value: 'Band 4 '}
    - {name: band_5, search_key: long_name, search_value: 'Band 5 '}
    - {name: band_6, search_key: long_name, search_value: 'Band 6 '}
    - {name: band_7, search_key: long_name, search_value: 'Band 7 '}
    - {name: band_9, search_key: long_name, search_value: 'Band 9 '}
    - {name: band_10, search_key: long_name, search_value: 'Band 10 '}
    - {name: band_11, search_key: long_name, search_value: 'Band 11 '}
    batch_size: 1440000
    file_pattern: .*\.hdf
    get_y_func: elm.pipeline.tests.util:example_get_y_func_continuous
    reader: hdf4_example
    sample_args_generator: iter_files_recursively
    sample_from_args_func: elm.sample_util.samplers:image_selection
    selection_kwargs: {metadata_filter: 'elm.sample_util.metadata_selection:example_meta_is_day',
      top_dir: 'env:ELM_EXAMPLE_DATA_PATH'}
ensembles:
  no_ensemble: {init_ensemble_size: 1, ngen: 1, partial_fit_batches: 1, saved_ensemble_size: 1}
pipeline:
- data_source: NPP_DSRF1KD_L2GD
  sample_pipeline:
  - {select_canvas: band_1}
  - {flatten: C}
  - {sklearn_preprocessing: require_positive}
  - {drop_na_rows: true}
  - {flatten: C}
  - {random_sample: 500}
  - {get_y: true}
  steps:
  - {method: fit, train: kmeans}
  - {predict: kmeans}
predict:
  kmeans: {}
readers:
  hdf4_example: {load_array: 'elm.readers.hdf4:load_hdf4_array', load_meta: 'elm.readers.hdf4:load_hdf4_meta'}
sample_args_generators: {iter_files_recursively: 'elm.readers.local_file_iterators:iter_files_recursively',
  tif_file_gen: 'elm.readers.local_file_iterators:iter_dirs_of_dirs'}
sklearn_preprocessing:
  require_positive:
    func: elm.sample_util.encoding_scaling:require_positive
    func_kwargs: {small_num: 0.0001}
    method: FunctionTransformer
train:
  kmeans:
    ensemble: no_ensemble
    ensemble_kwargs: {init_ensemble_size: 2, ngen: 1, partial_fit_batches: 1, saved_ensemble_size: 1}
    fit_method: fit
    model_init_class: sklearn.linear_model:LassoLarsCV
    model_init_kwargs: {max_iter: 10, n_jobs: -1}
    model_scoring: null
    model_selection: null
    output_tag: kmeans
transform:
  pca:
    ensemble: no_ensemble
    model_init_class: sklearn.decomposition:IncrementalPCA
    model_init_kwargs: {n_components: 2}
    model_scoring: null
