package:
  name: elm
  version: 0.0.0

build:
  number: 0
  pin_depends: record

requirements:
  build:
    - python
    - setuptools
  run:
    - python # [py35]
    - bokeh
    - dask
    - distributed
    - gdal
    - h5py
    - jupyter
    - krb5
    - matplotlib
    - netcdf4
    - networkx
    - numba
    - numpy
    - pandas
    - pytest
    - rasterio
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - tblib
    - xarray
    - yaml

about:
  home: http://github.com/ContinuumIO/elm
  license: MIT

extra:
  maintainers:
    - Peter Steinberg - Continuum Analytics - psteinberg [at] continuum [dot] io

