package:
  name: elm
  version: 0.0.0

build:
  number: 0
  pin_depends: record


requirements:
  build:
    - python
    - setuptools
  run:
    - python # [py35]
    - blaze
    - bokeh
    - dask
    - datashader
    - distributed
    - fiona
    - gdal
    - h5py
    - jupyter
    - krb5
    - matplotlib
    - netcdf4
    - networkx
    - numba
    - numpy
    - pandas
    - pyproj
    - pytest
    - rasterio
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - shapely
    - statsmodels
    - tblib
    - xarray
    - yaml


about:
  home: http://github.com/ContinuumIO/nasasbir
  license: MIT
